export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const START_DOWNLOAD_TASK = 'START_DOWNLOAD_TASK';
export const DOWNLOAD_TASK_SUCCESS = 'DOWNLOAD_TASK_SUCCESS';
export const DOWNLOAD_TASK_ERROR = 'DOWNLOAD_TASK_ERROR';

export const GET_TASK_DELETE = 'GET_TASK_DELETE';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_ERROR = 'TASK_DELETE_ERROR';

export const GET_TASK_EDIT = 'GET_TASK_EDIT';
export const START_EDIT_TASK = 'START_EDIT_TASK';
export const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS';
export const TASK_EDIT_ERROR = 'TASK_EDIT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const NONE_ALERT = 'NONE_ALERT';

